/*******************************************************************************
 *  Copyright (c) 2019, 2022 lucendar.com.
 *  All rights reserved.
 *
 *  Contributors:
 *     KwanKin Yau (alphax@vip.163.com) - initial API and implementation
 *******************************************************************************/
package com.lucendar.strm.common.strm.stored;

import java.util.StringJoiner;

/**
 * Register a terminal A/V upload request.
 */
public class RegisterAvUploadReq implements AbstractAvUpload {

    private String reqId;
    private String simNo;
    private String startTm;
    private Long sz;
    private String cb;

    public RegisterAvUploadReq() {
    }

    public RegisterAvUploadReq(String reqId, String simNo, String startTm, Long sz, String cb) {
        this.reqId = reqId;
        this.simNo = simNo;
        this.startTm = startTm;
        this.sz = sz;
        this.cb = cb;
    }

    /**
     * Get the A/V upload request ID, must be unique among all A/V upload request.
     * Can be `null`, if so then the `reqId` will be generated by the service and returned in `RegisterAvUploadResult`.
     * If supplied, it must satisfy {@link com.lucendar.strm.common.StreamingApi#isValidReqId(String)}.
     *
     * @return A/V upload request ID. `null` if the `reqId` generated by service.
     */
    @Override
    public String getReqId() {
        return reqId;
    }

    /**
     * Get `simNo` of the terminal.
     *
     * @return `simNo` of the terminal.
     */
    @Override
    public String getSimNo() {
        return simNo;
    }

    /**
     * Get the start time of the terminal stored AV file. Date time format: `yyyy-MM-dd HH:mm:ss`.
     *
     * @return start time of the terminal stored AV file.
     */
    @Override
    public String getStartTm() {
        return startTm;
    }

    /**
     * Get the base callback url of FTP notification(for `/upload` and `/upload/progress`).
     *
     * @return base callback url of FTP notification.
     */
    @Override
    public String getCb() {
        return cb;
    }

    /**
     * The claimed size of the A/V file.
     *
     * @return claimed size of the A/V file.
     */
    @Override
    public Long getSz() {
        return sz;
    }

    public void setReqId(String reqId) {
        this.reqId = reqId;
    }

    public void setSimNo(String simNo) {
        this.simNo = simNo;
    }

    public void setStartTm(String startTm) {
        this.startTm = startTm;
    }

    public void setSz(Long sz) {
        this.sz = sz;
    }

    public void setCb(String cb) {
        this.cb = cb;
    }

    @Override
    public String toString() {
        return new StringJoiner(", ", RegisterAvUploadReq.class.getSimpleName() + "[", "]")
                .add("reqId='" + reqId + "'")
                .add("simNo='" + simNo + "'")
                .add("startTm='" + startTm + "'")
                .add("sz=" + sz)
                .add("cb='" + cb + "'")
                .toString();
    }
}
